Repository GepardGraphics/gepard, pull requests merged in 2018-10, with the labels that each got.

#117 Terminate the window of examples gracefully when the close button is …
  apps/examples/fill-rect/fill-rect.cpp
  apps/examples/path-clock/path-clock.cpp
  apps/examples/render-thread/main.cpp
  apps/examples/savanna-benchmark/savanna-benchmarks.cpp
  src/surfaces/gepard-xsurface.h
Labels: example

#118 Fix minor issues
  src/utils/gepard-types.cpp
  src/utils/gepard-types.h
Labels: important

#122 [GLES2] Fix setting of texture sampler
  src/engines/gles2/gepard-gles2-fill-path.cpp
Labels: backend, bug, important

#127 Restrict include visibility in libgepard
  src/CMakeLists.txt
Labels: bug, infrastructure

#128 Add install target for libgepard
  src/CMakeLists.txt
  tools/build.py
Labels: infrastructure

#131 Fix svggepard build
  apps/pygepard/CMakeLists.txt
  apps/svggepard/CMakeLists.txt
Labels: critical, example, important

#140 Add missing license to the VulkanShaders.cmake
  cmake/VulkanShaders.cmake
Labels: enhancement

#144 Enable WSI extension in all vulkan instance
  src/engines/vulkan/gepard-vulkan.cpp
Labels: backend, bug, critical
